#page title
page_title                                : Pines                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
# ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
# ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
# playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Pines                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover the great outdoors with Pines, your ultimate camping campanion.<br><br>Elegantly crafted and filled to the brim with camping experience, Pines unfolds a world of serene campsites, inviting you to explore nature's most peaceful retreats.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Blue Mountain Studios, LLC                              
your_link                                 :                    
your_city                                 : Birmingham, AL                                
email_address                             : hello@lemonschedules.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Know Where You're Going
    description                           : Whether it's an epic National Park or a humble State Park in your backyard, Pines can show you the way.
    fontawesome_icon_name                 : calendar
    even_or_odd                           : even
    image_url                             : assets/screenshot/2.png
  
  - title                                 : What to Do
    description                           : TODO - What to do text goes here...explain how the app shows you what you can do
    fontawesome_icon_name                 : calendar
    even_or_odd                           : odd
    image_url                             : assets/screenshot/3.png

  - title                                 : Plan Ahead
    description                           : Know what the weather looks like before you go.
    fontawesome_icon_name                 : calendar
    even_or_odd                           : even
    image_url                             : assets/screenshot/4.png

  - title                                 : Always Know What You'll Find at That Campsite
    description                           : With Pines, you'll always know what to expect when you arrive at that campsite.
    fontawesome_icon_name                 : calendar
    even_or_odd                           : full
    image_url                             : assets/screenshot/5.png

bottom_paragraph                          : Pines is a family operation. The concept for Pines came from brainstorming solutions to real life challenges at the dinner table. Thanks for supporting our small business and joining our family!

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.9
topbar_title_color                        : "#ffffff"

cover_image                               : assets/pines.jpg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#5E936F"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#5E936F"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#5E936F"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
